services:
  postgres:
    image: postgres:latest
    container_name: CarShop.Db
    environment:
      POSTGRES_DB: "web_library"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql
      
